spring:
  application:
    name: Auth-Service        
  config:
    import: optional:configserver:http://localhost:2222/
    
    
   
auth-service:
     messages:
       userReg: User Created
       userRegErr: User Craetion Failed
       login: Login Success
       loginErr: Invalid Credentials    